PROJECT_NAME={{ project_name }}
IMAGE_NAME={{ image_name }}

.PHONY: up down save commit

up:
	docker-compose up -d

down:
	docker-compose down

save:
	docker commit $(shell docker ps -q -f name=$(PROJECT_NAME)) $(PROJECT_NAME)_snapshot

commit:
	docker commit $(shell docker ps -q -f name=$(PROJECT_NAME)) $(PROJECT_NAME):latest # Tag the snapshot as project_name:latest
	docker-compose down
	docker-compose up -d